#!/usr/bin/env python3
"""PocketOps demo mock server.

Serves:
- POST /api/pocketops/auth/login
- GET  /api/pocketops/bootstrap/manifest
- POST /api/pocketops/materials/query
- POST /api/pocketops/work-orders/submit
- GET/HEAD /files/...

The server reads the real bundled knowledge graph from the Android assets
directory so the phone can demonstrate a true remote bootstrap sync.
"""

from __future__ import annotations

import argparse
import hmac
import hashlib
import io
import json
import secrets
import socket
import sys
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Dict, Iterable, Sequence, Tuple
from urllib.parse import urlparse
import zipfile


ROOT = Path(__file__).resolve().parents[1]
KNOWLEDGE_GRAPH_RELATIVE_PATH = Path(
    "Android/src/app/src/main/assets/maintenance/knowledge_graph.json"
)
DEFAULT_SYNC_VERSION = "2026-05-06.demo.1"
DEFAULT_MIN_SUPPORTED_APP_VERSION = "4.8"
DEFAULT_DEMO_USERNAME = "engineer"
DEFAULT_DEMO_PASSWORD = "PocketOps@2026"
DEFAULT_TOKEN_TTL_SECONDS = 8 * 60 * 60


@dataclass(frozen=True)
class FileAsset:
    path: str
    content: bytes
    mime_type: str
    sha256: str

    @property
    def size_bytes(self) -> int:
        return len(self.content)


ASSETS: Dict[str, FileAsset] = {}
GRAPH_STATS: Dict[str, object] = {}
AUTH_SESSIONS: Dict[str, Dict[str, object]] = {}
SUBMITTED_WORK_ORDERS: Dict[str, Dict[str, object]] = {}


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def build_pdf_bytes(title: str, subtitle: str) -> bytes:
    lines = [
        "BT /F1 20 Tf 36 110 Td ({}) Tj ET".format(escape_pdf_text(title)),
        "BT /F1 12 Tf 36 88 Td ({}) Tj ET".format(escape_pdf_text(subtitle)),
        "BT /F1 12 Tf 36 64 Td (Generated by PocketOps demo mock server.) Tj ET",
    ]
    stream = "\n".join(lines).encode("ascii")
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 420 180] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>",
        b"<< /Length %d >>\nstream\n%s\nendstream" % (len(stream), stream),
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    buffer = io.BytesIO()
    buffer.write(b"%PDF-1.4\n")
    offsets = [0]
    for index, body in enumerate(objects, start=1):
        offsets.append(buffer.tell())
        buffer.write(f"{index} 0 obj\n".encode("ascii"))
        buffer.write(body)
        buffer.write(b"\nendobj\n")

    xref_offset = buffer.tell()
    buffer.write(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
    buffer.write(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        buffer.write(f"{offset:010d} 00000 n \n".encode("ascii"))
    buffer.write(
        (
            "trailer\n"
            f"<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
            "startxref\n"
            f"{xref_offset}\n"
            "%%EOF\n"
        ).encode("ascii")
    )
    return buffer.getvalue()


def escape_pdf_text(text: str) -> str:
    return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def build_zip_bytes(files: Dict[str, str]) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for name, content in files.items():
            archive.writestr(name, content)
    return buffer.getvalue()


def build_work_orders_payload() -> bytes:
    payload = {
        "workOrders": [
            {
                "id": "wo_1024",
                "equipment": "Forklift-03",
                "fault": "Lift speed dropped",
                "resolution": "Replaced hydraulic seal kit and flushed oil line",
                "date": "2026-04-08",
                "downtime": "2.5h",
                "cost": "560 CNY",
            },
            {
                "id": "wo_2048",
                "equipment": "Forklift-03",
                "fault": "Steering is heavy",
                "resolution": "Replaced pressure relief valve",
                "date": "2026-03-14",
                "downtime": "1.5h",
                "cost": "340 CNY",
            },
        ]
    }
    return json.dumps(payload, indent=2).encode("utf-8")


def iter_knowledge_graph_candidates() -> Sequence[Path]:
    candidates: list[Path] = [
        ROOT / KNOWLEDGE_GRAPH_RELATIVE_PATH,
        ROOT.parent / KNOWLEDGE_GRAPH_RELATIVE_PATH,
    ]

    # Probe sibling project folders without assuming a specific release-style
    # Android repo directory name.
    workspace_root = ROOT.parent
    try:
        siblings = sorted(path for path in workspace_root.iterdir() if path.is_dir())
    except OSError:
        siblings = []

    for sibling in siblings:
        candidates.append(sibling / KNOWLEDGE_GRAPH_RELATIVE_PATH)
        try:
            nested_children = sorted(path for path in sibling.iterdir() if path.is_dir())
        except OSError:
            nested_children = []
        for nested in nested_children:
            candidates.append(nested / KNOWLEDGE_GRAPH_RELATIVE_PATH)

    unique_candidates: list[Path] = []
    seen: set[Path] = set()
    for candidate in candidates:
        if candidate not in seen:
            unique_candidates.append(candidate)
            seen.add(candidate)
    return tuple(unique_candidates)


def resolve_knowledge_graph_path(explicit_path: Path | None = None) -> Path:
    if explicit_path is not None:
        path = explicit_path.expanduser().resolve()
        if not path.exists():
            raise FileNotFoundError(f"knowledge graph not found: {path}")
        return path

    for candidate in iter_knowledge_graph_candidates():
        if candidate.exists():
            return candidate

    tried = "\n".join(f"  - {candidate}" for candidate in iter_knowledge_graph_candidates())
    raise FileNotFoundError(
        "Could not locate maintenance knowledge graph. Tried:\n"
        f"{tried}\n"
        "Pass --knowledge-graph <path> to override."
    )


def load_knowledge_graph_bytes(knowledge_graph_path: Path) -> bytes:
    if not knowledge_graph_path.exists():
        raise FileNotFoundError(f"knowledge graph not found: {knowledge_graph_path}")
    return knowledge_graph_path.read_bytes()


def build_assets(knowledge_graph_path: Path) -> Dict[str, FileAsset]:
    knowledge_graph_bytes = load_knowledge_graph_bytes(knowledge_graph_path)
    work_orders_bytes = build_work_orders_payload()
    sop_zip_bytes = build_zip_bytes(
        {
            "sop/inspection_checklist.txt": "1. Confirm pressure level.\n2. Inspect hose leakage.\n3. Verify lift response.\n",
            "sop/parts_list.txt": "Hydraulic seal kit\nPressure relief valve\nFilter element\n",
        }
    )
    manual_pdf = build_pdf_bytes(
        "PocketOps Demo SOP",
        "Hydraulic pump inspection workflow for Forklift-03",
    )
    history_zip = build_zip_bytes(
        {
            "history/work_order_1024.txt": "WO-1024: replaced seal kit and flushed oil line.",
            "history/work_order_2048.txt": "WO-2048: steering pressure restored after valve replacement.",
            "photos/README.txt": "Placeholder attachment bundle for the PocketOps demo.",
        }
    )
    summary_json = json.dumps(
        {
            "notes": [
                "Remote bootstrap used repo asset knowledge_graph.json",
                "This file is returned as a sample structured material",
            ]
        },
        indent=2,
    ).encode("utf-8")

    def asset(path: str, content: bytes, mime_type: str) -> FileAsset:
        return FileAsset(path=path, content=content, mime_type=mime_type, sha256=sha256_bytes(content))

    return {
        "/files/core/knowledge_graph.json": asset(
            "/files/core/knowledge_graph.json",
            knowledge_graph_bytes,
            "application/json; charset=utf-8",
        ),
        "/files/core/work_orders.json": asset(
            "/files/core/work_orders.json",
            work_orders_bytes,
            "application/json; charset=utf-8",
        ),
        "/files/docs/sop_docs.zip": asset(
            "/files/docs/sop_docs.zip",
            sop_zip_bytes,
            "application/zip",
        ),
        "/files/materials/hydraulic_pump_sop.pdf": asset(
            "/files/materials/hydraulic_pump_sop.pdf",
            manual_pdf,
            "application/pdf",
        ),
        "/files/materials/history_attachments.zip": asset(
            "/files/materials/history_attachments.zip",
            history_zip,
            "application/zip",
        ),
        "/files/materials/diagnostic_summary.json": asset(
            "/files/materials/diagnostic_summary.json",
            summary_json,
            "application/json; charset=utf-8",
        ),
    }


def bootstrap_assets(knowledge_graph_path: Path) -> None:
    global ASSETS, GRAPH_STATS
    ASSETS = build_assets(knowledge_graph_path)
    GRAPH_STATS = json.loads(ASSETS["/files/core/knowledge_graph.json"].content.decode("utf-8"))


def build_manifest(
    base_url: str,
    sync_version: str = DEFAULT_SYNC_VERSION,
    min_supported_app_version: str = DEFAULT_MIN_SUPPORTED_APP_VERSION,
) -> Dict[str, object]:
    knowledge_graph = ASSETS["/files/core/knowledge_graph.json"]
    work_orders = ASSETS["/files/core/work_orders.json"]
    sop_docs = ASSETS["/files/docs/sop_docs.zip"]
    node_count = len(GRAPH_STATS.get("nodes", []))
    edge_count = len(GRAPH_STATS.get("edges", []))
    return {
        "syncVersion": sync_version,
        "minSupportedAppVersion": min_supported_app_version,
        "generatedAt": datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "summary": {
            "equipmentCount": 32,
            "faultCaseCount": 286,
            "graphNodeCount": node_count,
            "graphEdgeCount": edge_count,
            "sopCount": 168,
            "partCount": 523,
            "workOrderCount": 2156,
            "personnelCount": 48,
        },
        "displaySteps": [
            {"key": "equipment", "title": "Sync equipment records", "detail": "32 devices across 6 workshops"},
            {"key": "work_orders", "title": "Sync work order history", "detail": "2156 records in last 3 years"},
            {"key": "knowledge_graph", "title": "Sync diagnosis knowledge graph", "detail": f"{node_count} nodes / {edge_count} edges"},
        ],
        "resources": [
            {
                "id": "knowledge_graph",
                "name": "Diagnosis knowledge graph",
                "category": "core",
                "requiredAtBoot": True,
                "version": sync_version,
                "sizeBytes": knowledge_graph.size_bytes,
                "sha256": knowledge_graph.sha256,
                "mimeType": "application/json",
                "downloadUrl": f"{base_url}{knowledge_graph.path}",
                "localPath": "core/knowledge_graph.json",
                "zip": False,
                "unzipDir": "",
            },
            {
                "id": "work_orders",
                "name": "Work order history",
                "category": "core",
                "requiredAtBoot": False,
                "version": sync_version,
                "sizeBytes": work_orders.size_bytes,
                "sha256": work_orders.sha256,
                "mimeType": "application/json",
                "downloadUrl": f"{base_url}{work_orders.path}",
                "localPath": "core/work_orders.json",
                "zip": False,
                "unzipDir": "",
            },
            {
                "id": "sop_docs",
                "name": "SOP package",
                "category": "docs",
                "requiredAtBoot": False,
                "version": sync_version,
                "sizeBytes": sop_docs.size_bytes,
                "sha256": sop_docs.sha256,
                "mimeType": "application/zip",
                "downloadUrl": f"{base_url}{sop_docs.path}",
                "localPath": "docs/sop_docs.zip",
                "zip": True,
                "unzipDir": "docs/sop_docs",
            },
        ],
    }


def build_materials(base_url: str, payload: Dict[str, object]) -> Dict[str, object]:
    equipment_id = str(payload.get("equipmentId") or "eq_demo_001")
    symptom_id = str(payload.get("symptomId") or "sym_demo_001")
    work_order_ids = payload.get("workOrderIds") or ["wo_1024"]
    if not isinstance(work_order_ids, list):
        work_order_ids = ["wo_1024"]

    pdf_asset = ASSETS["/files/materials/hydraulic_pump_sop.pdf"]
    zip_asset = ASSETS["/files/materials/history_attachments.zip"]
    json_asset = ASSETS["/files/materials/diagnostic_summary.json"]
    return {
        "materials": [
            {
                "id": "mat_demo_sop",
                "title": "Hydraulic pump SOP",
                "type": "pdf",
                "category": "sop",
                "sizeBytes": pdf_asset.size_bytes,
                "sha256": pdf_asset.sha256,
                "mimeType": "application/pdf",
                "version": "v1",
                "previewable": True,
                "shareable": True,
                "downloadUrl": f"{base_url}{pdf_asset.path}",
                "thumbnailUrl": "",
                "linkedEntities": {
                    "equipmentIds": [equipment_id],
                    "symptomIds": [symptom_id],
                    "workOrderIds": work_order_ids,
                },
            },
            {
                "id": "mat_demo_history",
                "title": "History attachments bundle",
                "type": "zip",
                "category": "work_order_attachment",
                "sizeBytes": zip_asset.size_bytes,
                "sha256": zip_asset.sha256,
                "mimeType": "application/zip",
                "version": "v1",
                "previewable": False,
                "shareable": True,
                "downloadUrl": f"{base_url}{zip_asset.path}",
                "thumbnailUrl": "",
                "linkedEntities": {
                    "equipmentIds": [equipment_id],
                    "symptomIds": [symptom_id],
                    "workOrderIds": work_order_ids,
                },
            },
            {
                "id": "mat_demo_summary",
                "title": "Diagnostic summary",
                "type": "json",
                "category": "report",
                "sizeBytes": json_asset.size_bytes,
                "sha256": json_asset.sha256,
                "mimeType": "application/json",
                "version": "v1",
                "previewable": True,
                "shareable": True,
                "downloadUrl": f"{base_url}{json_asset.path}",
                "thumbnailUrl": "",
                "linkedEntities": {
                    "equipmentIds": [equipment_id],
                    "symptomIds": [symptom_id],
                    "workOrderIds": work_order_ids,
                },
            },
        ]
    }


def store_submitted_work_order(payload: Dict[str, object]) -> Dict[str, object]:
    work_order_id = str(payload.get("workOrderId") or "")
    client_submission_id = str(payload.get("clientSubmissionId") or "")
    if not work_order_id:
        raise ValueError("missing workOrderId")
    if not client_submission_id:
        raise ValueError("missing clientSubmissionId")

    server_id = f"server-{work_order_id}"
    submitted_at = datetime.now(timezone.utc).isoformat()
    SUBMITTED_WORK_ORDERS[client_submission_id] = {
        "serverWorkOrderId": server_id,
        "submittedAt": submitted_at,
        "payload": payload,
    }
    return {
        "accepted": True,
        "serverWorkOrderId": server_id,
        "clientSubmissionId": client_submission_id,
        "submittedAt": submitted_at,
        "queuedCount": len(SUBMITTED_WORK_ORDERS),
    }


def authenticate_demo_user(
    username: str,
    password: str,
    expected_username: str,
    expected_password: str,
) -> bool:
    return hmac.compare_digest(username, expected_username) and hmac.compare_digest(password, expected_password)


def create_auth_session(username: str) -> Dict[str, object]:
    token = secrets.token_urlsafe(32)
    expires_at = datetime.now(timezone.utc) + timedelta(seconds=DEFAULT_TOKEN_TTL_SECONDS)
    session = {
        "accessToken": token,
        "userId": username,
        "displayName": "维修工程师",
        "role": "maintenance_engineer",
        "expiresInSeconds": DEFAULT_TOKEN_TTL_SECONDS,
        "expiresAt": expires_at,
    }
    AUTH_SESSIONS[token] = session
    return session


def public_auth_session(session: Dict[str, object]) -> Dict[str, object]:
    return {
        "accessToken": session["accessToken"],
        "userId": session["userId"],
        "displayName": session["displayName"],
        "role": session["role"],
        "expiresInSeconds": session["expiresInSeconds"],
    }


def parse_json_body(handler: BaseHTTPRequestHandler) -> Dict[str, object]:
    length = int(handler.headers.get("Content-Length", "0"))
    raw = handler.rfile.read(length) if length > 0 else b"{}"
    if not raw:
        return {}
    return json.loads(raw.decode("utf-8"))


def parse_range_header(range_header: str | None, size: int) -> Tuple[int, int] | None:
    if not range_header or not range_header.startswith("bytes="):
        return None
    first_part = range_header[len("bytes="):].split(",", 1)[0].strip()
    if "-" not in first_part:
        raise ValueError("invalid byte range")
    start_text, end_text = first_part.split("-", 1)
    if start_text == "":
        if not end_text:
            raise ValueError("invalid suffix range")
        suffix_length = int(end_text)
        if suffix_length <= 0:
            raise ValueError("invalid suffix range")
        start = max(0, size - suffix_length)
        end = size - 1
        return (start, end)

    start = int(start_text)
    end = size - 1 if end_text == "" else int(end_text)
    if start < 0 or start >= size or end < start:
        raise ValueError("range out of bounds")
    return (start, min(end, size - 1))


class PocketOpsDemoHandler(BaseHTTPRequestHandler):
    server_version = "PocketOpsMock/1.1"

    def do_GET(self) -> None:  # noqa: N802
        self.handle_request(with_body=True)

    def do_HEAD(self) -> None:  # noqa: N802
        self.handle_request(with_body=False)

    def do_POST(self) -> None:  # noqa: N802
        parsed = urlparse(self.path)

        if parsed.path == "/api/pocketops/auth/login":
            self.handle_login()
            return

        if parsed.path == "/api/pocketops/materials/query":
            if not self.require_auth():
                return

            try:
                payload = parse_json_body(self)
            except json.JSONDecodeError as exc:
                self.send_json({"error": f"invalid_json: {exc}"}, status=HTTPStatus.BAD_REQUEST)
                return

            self.send_json(build_materials(self.base_url(), payload))
            return

        if parsed.path == "/api/pocketops/work-orders/submit":
            if not self.require_auth():
                return

            try:
                payload = parse_json_body(self)
                result = store_submitted_work_order(payload)
            except json.JSONDecodeError as exc:
                self.send_json({"error": f"invalid_json: {exc}"}, status=HTTPStatus.BAD_REQUEST)
                return
            except ValueError as exc:
                self.send_json({"error": str(exc)}, status=HTTPStatus.BAD_REQUEST)
                return

            self.send_json(result, status=HTTPStatus.CREATED)
            return

        self.send_json({"error": "not_found"}, status=HTTPStatus.NOT_FOUND)

    def handle_login(self) -> None:
        try:
            payload = parse_json_body(self)
        except json.JSONDecodeError as exc:
            self.send_json({"error": f"invalid_json: {exc}"}, status=HTTPStatus.BAD_REQUEST)
            return

        username = str(payload.get("username") or "")
        password = str(payload.get("password") or "")
        if not authenticate_demo_user(
            username=username,
            password=password,
            expected_username=getattr(self.server, "demo_username", DEFAULT_DEMO_USERNAME),
            expected_password=getattr(self.server, "demo_password", DEFAULT_DEMO_PASSWORD),
        ):
            self.send_json({"error": "invalid_credentials"}, status=HTTPStatus.UNAUTHORIZED)
            return

        self.send_json(public_auth_session(create_auth_session(username)))

    def handle_request(self, with_body: bool) -> None:
        parsed = urlparse(self.path)
        if parsed.path == "/api/pocketops/bootstrap/manifest":
            if not self.require_auth(with_body=with_body):
                return
            self.send_json(
                build_manifest(
                    self.base_url(),
                    sync_version=getattr(self.server, "sync_version", DEFAULT_SYNC_VERSION),
                    min_supported_app_version=getattr(
                        self.server,
                        "min_supported_app_version",
                        DEFAULT_MIN_SUPPORTED_APP_VERSION,
                    ),
                ),
                with_body=with_body,
            )
            return

        asset = ASSETS.get(parsed.path)
        if asset is None:
            self.send_json({"error": "not_found"}, status=HTTPStatus.NOT_FOUND, with_body=with_body)
            return

        if not self.require_auth(with_body=with_body):
            return

        self.send_asset(asset, with_body=with_body)

    def require_auth(self, with_body: bool = True) -> bool:
        header = self.headers.get("Authorization", "")
        if not header.startswith("Bearer "):
            self.send_json({"error": "missing_bearer_token"}, status=HTTPStatus.UNAUTHORIZED, with_body=with_body)
            return False

        token = header.removeprefix("Bearer ").strip()
        session = AUTH_SESSIONS.get(token)
        if session is None:
            self.send_json({"error": "invalid_bearer_token"}, status=HTTPStatus.UNAUTHORIZED, with_body=with_body)
            return False

        expires_at = session.get("expiresAt")
        if not isinstance(expires_at, datetime) or expires_at <= datetime.now(timezone.utc):
            AUTH_SESSIONS.pop(token, None)
            self.send_json({"error": "expired_bearer_token"}, status=HTTPStatus.UNAUTHORIZED, with_body=with_body)
            return False

        return True

    def base_url(self) -> str:
        host = self.headers.get("Host")
        if host:
            return f"http://{host}"
        server_host, server_port = self.server.server_address[:2]
        return f"http://{server_host}:{server_port}"

    def send_json(
        self,
        payload: Dict[str, object],
        status: HTTPStatus = HTTPStatus.OK,
        with_body: bool = True,
    ) -> None:
        content = json.dumps(payload, ensure_ascii=False, indent=2).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(content)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        if with_body:
            self.wfile.write(content)

    def send_asset(self, asset: FileAsset, with_body: bool) -> None:
        range_header = self.headers.get("Range")
        status = HTTPStatus.OK
        content = asset.content
        start = 0
        end = len(content) - 1
        try:
            parsed_range = parse_range_header(range_header, len(content))
        except ValueError:
            self.send_response(HTTPStatus.REQUESTED_RANGE_NOT_SATISFIABLE)
            self.send_header("Content-Range", f"bytes */{len(content)}")
            self.end_headers()
            return

        if parsed_range is not None:
            start, end = parsed_range
            content = asset.content[start : end + 1]
            status = HTTPStatus.PARTIAL_CONTENT

        self.send_response(status)
        self.send_header("Content-Type", asset.mime_type)
        self.send_header("Content-Length", str(len(content)))
        self.send_header("Accept-Ranges", "bytes")
        self.send_header("ETag", asset.sha256)
        self.send_header("Cache-Control", "no-store")
        if status == HTTPStatus.PARTIAL_CONTENT:
            self.send_header("Content-Range", f"bytes {start}-{end}/{len(asset.content)}")
        self.end_headers()
        if with_body:
            self.wfile.write(content)

    def log_message(self, fmt: str, *args: object) -> None:
        sys.stdout.write("%s - - [%s] %s\n" % (self.address_string(), self.log_date_time_string(), fmt % args))


def iter_candidate_urls(host: str, port: int) -> Iterable[str]:
    yield f"http://127.0.0.1:{port}"
    if host not in {"127.0.0.1", "localhost", "0.0.0.0", "::"}:
        yield f"http://{host}:{port}"
    try:
        lan_ip = socket.gethostbyname(socket.gethostname())
    except OSError:
        return
    if lan_ip and lan_ip not in {"127.0.0.1", host}:
        yield f"http://{lan_ip}:{port}"


def main() -> None:
    parser = argparse.ArgumentParser(description="Run the PocketOps demo mock server.")
    parser.add_argument("--host", default="0.0.0.0", help="Bind host, default: 0.0.0.0")
    parser.add_argument("--port", type=int, default=8080, help="Bind port, default: 8080")
    parser.add_argument(
        "--knowledge-graph",
        type=Path,
        default=None,
        help="Override Android assets knowledge_graph.json path.",
    )
    parser.add_argument(
        "--sync-version",
        default=DEFAULT_SYNC_VERSION,
        help=f"Manifest syncVersion, default: {DEFAULT_SYNC_VERSION}",
    )
    parser.add_argument(
        "--min-supported-app-version",
        default=DEFAULT_MIN_SUPPORTED_APP_VERSION,
        help=f"Manifest minSupportedAppVersion, default: {DEFAULT_MIN_SUPPORTED_APP_VERSION}",
    )
    parser.add_argument(
        "--demo-username",
        default=DEFAULT_DEMO_USERNAME,
        help=f"Demo login username, default: {DEFAULT_DEMO_USERNAME}",
    )
    parser.add_argument(
        "--demo-password",
        default=DEFAULT_DEMO_PASSWORD,
        help="Demo login password.",
    )
    args = parser.parse_args()

    knowledge_graph_path = resolve_knowledge_graph_path(args.knowledge_graph)
    bootstrap_assets(knowledge_graph_path)

    server = ThreadingHTTPServer((args.host, args.port), PocketOpsDemoHandler)
    server.sync_version = args.sync_version
    server.min_supported_app_version = args.min_supported_app_version
    server.demo_username = args.demo_username
    server.demo_password = args.demo_password
    print("PocketOps demo mock server is running.")
    print(f"Knowledge graph source: {knowledge_graph_path}")
    print(f"Manifest syncVersion: {args.sync_version}")
    print(f"Manifest minSupportedAppVersion: {args.min_supported_app_version}")
    print(f"Demo login username: {args.demo_username}")
    print(f"Demo login password: {args.demo_password}")
    print("Use one of these URLs in the Android demo:")
    for url in dict.fromkeys(iter_candidate_urls(args.host, args.port)):
        print(f"  {url}")
    print("If you use adb reverse, configure the phone with: http://127.0.0.1:8080")
    print("Press Ctrl+C to stop.")

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopping server...")
    finally:
        server.server_close()


if __name__ == "__main__":
    main()
